#!/bin/bash
HEADER_COL='\033[0;36m'
COMMAND_COL='\033[0;33m'
INVALID_COL='\033[0;31m'
RESET_COL='\033[0m'

wallDir="$HOME/Pictures/Wallpapers"

case "$1" in
	set)
		if [[ ! -e "$wallDir/$2" ]]; then
			echo "Wallpaper does not exist"
			exit 1
		fi
		ln -nsf "$wallDir/$2" "$wallDir/active"
		touch "$wallDir/lock"
		feh --bg-fill "$wallDir/active"
		;;
	list)
		find "$wallDir" -type f \( -iname "*.jpg" -o -iname "*.png" \) -printf "%f\n"
		;;
	unlock)
		rm "$wallDir/lock"
		;;
	lock)
		touch "$wallDir/lock"
		;;
	apply)
		#Randomize wallpaper
		if [[ ! -e "$wallDir/lock" ]]; then
			ln -nsf "$(find $wallDir -type f -iname "*.jpg" -o -iname "*.png" | shuf -n 1)" "$wallDir/active"
		fi
		feh --bg-fill "$wallDir/active"
		;;
	get)
		cd "$wallDir" && wget $2 || exit 1
		;;
	current)
		readlink "$wallDir/active" || exit 1
		;;
	delete)
		URL=$2
		if [[ -z $URL ]]; then
			URL="$(readlink "$wallDir/active")"
		fi
		rm "$wallDir/$URL"
		;;
	*)

		printf "${HEADER_COL}"
		cat << "EOF"

        _....,_         _,...._
    _.-` _,..,_'.     .'_,..,_ `-._
     _,-`/ o \ '.     .' / o \`-,_     I saw that
      '-.\___/.-`     `-.\___/.-'

EOF
		printf "${RESET_COL}"

		echo -e "${INVALID_COL}Invalid option${RESET_COL}"
		echo ""
		echo -e "${INVALID_COL}Supported options are:${RESET_COL}"
		echo -e "${COMMAND_COL}set${RESET_COL} - set the given wallpaper as the current wallpaper and lock it"
		echo -e "${COMMAND_COL}unlock${RESET_COL} - unlock the wallpaper"
		echo -e "${COMMAND_COL}lock${RESET_COL} - lock the current wallpaper"
		echo -e "${COMMAND_COL}apply${RESET_COL} - apply wallpaper, randomizing it if lock is not set"
		echo -e "${COMMAND_COL}get${RESET_COL} - download wallpaper from url"
		echo -e "${COMMAND_COL}current${RESET_COL} - get the current wallpaper"
		echo -e "${COMMAND_COL}delete${RESET_COL} - delete wallpaper"
		exit 1
		;;
esac

