#! /bin/sh

bspc config border_width        3
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Steam floating=on
bspc rule -a feh floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# wallpaper
feh --bg-scale ~/Pictures/Wallpapers/active

# hotkeys
shxkd &
xbindkeys &

#Kill panel and restart
if [ $(pgrep 'panel') ]; then
		pgrep 'panel' | xargs kill -s 9
fi
~/.config/bar/panel.sh &

compton --config ~/.config/compton.conf -b
