#! /bin/bash

bspc config border_width        1
bspc config window_gap         24

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config focused_border_color '#AF865A'
bspc config normal_border_color '#4F4F4F'
bspc config urgent_border_color '#D17B49'
bspc config top_padding 17

#Setup workspaces
autorandr -c
bspwm_reorder

bspc rule -a Steam state=floating desktop=V follow=on
bspc rule -a feh state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a vlc state=floating
bspc rule -a Kupfer.py state=floating
bspc rule -a Screenkey manage=off

if [ -e "$BSPWM_TREE" ] ; then
	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

# polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# wallpaper
wallpaper apply

# hotkeys
sxhkd &
xbindkeys &

xsetroot -cursor_name left_ptr &

#Kill panel and restart
#if [ $(pgrep 'bard') ]; then
#		pgrep 'bard' | xargs kill -s 9
#fi
#~/.config/bar/panel.sh 2>/dev/null &
bard -c ~/.config/bard 1>&2 2>/dev/null &
#/home/delusional/bard/build/src/bard -c /home/delusional/.config/bard &

urxvtd &
xflux -l 57.0137 -g 9.9832 &

compton --config ~/.config/compton.conf -b

(sleep 1 &&	. ~/scripts/lock.sh) &
xkbcomp ~/.config/xkb/layout.xkb $DISPLAY

wmname LG3D
