#! /bin/bash

bspc config border_width        3
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DVI-I-2 -d I II III IV V 
bspc monitor DVI-I-3 -d VI VII VIII IX X 

bspc rule -a Steam floating=on
bspc rule -a feh floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

if [ -e "$BSPWM_TREE" ] ; then
	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

# polkit
/usr/lib/kde4/libexec/polkit-kde-authentication-agent-1 &

# wallpaper
feh --bg-scale ~/Pictures/Wallpapers/active

# hotkeys
shxkd &
xbindkeys &

#Kill panel and restart
if [ $(pgrep 'panel') ]; then
		pgrep 'panel' | xargs kill -s 9
fi
~/.config/bar/panel.sh &

xflux -l 57.0137 -g 9.9832 &

compton --config ~/.config/compton.conf -b
